-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- vim.keymap.set("n", "<leader>y", '"+y', { desc = "Yank to clipboard" }) -- normal mode copy
-- vim.keymap.set("v", "<leader>y", '"+y', { desc = "Yank to clipboard" }) -- visual mode copy
--
-- vim.keymap.set("n", "<leader>p", '"+p', { desc = "Paste from clipboard" })
-- vim.keymap.set("v", "<leader>p", '"+p', { desc = "Paste from clipboard" })
-- Custom save commands (safe: doesn't mess with built-in :e)
